<?php
/** @var \Eye4web\Zf2Board\Entity\BoardInterface[] $boards */
$boards = $this->boards;
?>
<h1><?=$this->translate('Boards')?></h1>
<table class="table">
    <thead>
    <tr>
        <td><?=$this->translate('ID')?></td>
        <td><?=$this->translate('Name')?></td>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($boards as $board) { ?>
        <tr>
            <td><?=$board->getId()?></td>
            <td><?=$board->getName()?></td>
        </tr>
    <?php } ?>
    </tbody>
</table>