<?php
/** @var \Eye4web\Zf2Board\Entity\BoardInterface[] $boards */
$boards = $this->boards;
?>
<h1><?=$this->translate('Boards')?></h1>
<table class="table">
    <thead>
    <tr>
        <td><?=$this->translate('ID')?></td>
        <td><?=$this->translate('Name')?></td>
        <td></td>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($boards as $board) { ?>
        <tr>
            <td><?=$board->getId()?></td>
            <td><?=$board->getName()?></td>
            <td>
                <div class="btn-group pull-right">
                    <a href="<?=$this->url('zfcadmin/zf2-board-admin/board/edit', ['id' => $board->getId()])?>" class="btn btn-primary"><?=$this->translate('Edit')?></a>
                    <a href="?delete=<?=$board->getId()?>" class="btn btn-danger"><?=$this->translate('Delete')?></a>
                </div>
            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>