<?php
/** @var \Eye4web\Zf2Board\Entity\BoardInterface[] $boards */
$boards = $this->boards;
?>
<h1><?=$this->translate('Boards')?></h1>
<table class="table">
    <thead>
    <tr>
        <td><?=$this->translate('ID')?></td>
        <td><?=$this->translate('Name')?></td>
        <td></td>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($boards as $board) { ?>
        <tr>
            <td><?=$board->getId()?></td>
            <td><?=$board->getName()?></td>
            <td style="text-align: right;">
                <a href="<?=$this->url('zfcadmin/zf2-board-admin/board/edit', ['id' => $board->getId()])?>" title="<?=$this->translate('Edit')?>" class="btn btn-primary">
                    <i class="glyphicon glyphicon-pencil"></i> <?=$this->translate('Edit')?>
                </a>

                <a href="?delete=<?=$board->getId()?>" title="<?=$this->translate('Delete')?>" class="btn btn-danger">
                    <i class="glyphicon glyphicon-remove"></i> <?=$this->translate('Delete')?>
                </a>
            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>