<?php
/** @var \Eye4web\Zf2Board\Entity\BoardInterface $board */
$board = $this->board;

/** @var \Eye4web\Zf2Board\Entity\TopicInterface[] $topics */
$topics = $this->topics;
?>
<h1><?=sprintf($this->translate('Topics posted in board "%s"'), $board->getName())?></h1>

<a href="<?=$this->url('zfcadmin/zf2-board-admin/board/list')?>" class="btn btn-link"><i class="glyphicon glyphicon-arrow-left"></i>&nbsp; <?=$this->translate('Back to board overview')?></a>

<table class="table">
    <thead>
    <tr>
        <td><?=$this->translate('ID')?></td>
        <td><?=$this->translate('Name')?></td>
        <td><?=$this->translate('User')?></td>
        <td><?=$this->translate('Date')?></td>
        <td></td>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($topics as $topic) { ?>
        <tr>
            <td><?=$topic->getId()?></td>
            <td><?=$topic->getName()?></td>
            <td><?=$this->zf2BoardHelper()->getAuthor($topic->getUser())->getFirstName()?> <?=$this->zf2BoardHelper()->getAuthor($topic->getUser())->getLastName()?></td>
            <td><?=$topic->getCreated()->format('Y/m/d H:i')?></td>
            <td style="text-align: right;">
                <a href="<?=$this->url('zfcadmin/zf2-board-admin/post/list', ['topic' => $topic->getId()])?>" class="btn btn-default"><i class="glyphicon glyphicon-th-list"></i> <?=$this->translate('Posts')?></a>
                <a href="<?=$this->url('zfcadmin/zf2-board-admin/topic/edit', ['id' => $topic->getId()])?>" class="btn btn-primary"><i class="glyphicon glyphicon-pencil"></i> <?=$this->translate('Edit')?></a>
                <a href="?delete=<?=$topic->getId()?>" class="btn btn-danger"><i class="glyphicon glyphicon-remove"></i> <?=$this->translate('Delete')?></a>
            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>